tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/core"

cask "java"

cask "caffeine"
cask "google-chrome"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "teamviewer"
cask "visual-studio-code"
cask "webstorm"
cask "daisydisk"
cask "duet"
cask "parallels-desktop"
cask "postman"

